spring:
  datasource:
    url: jdbc:h2:~/test;
    username: sa
    driver-class-name: org.h2.Driver
    authorization:
      secret: NBGiEbuWoH

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 730166977613-ebjk5hfak5mplpc5tl6e39fgnpl5h2gr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  jwt:
    header: cookies
    secret: YW5kMExYUmxjM1F0WVd4cWFtRmlZV1ZuYVMxcWQzUXRkR1Z6ZEMxaGJHcHFZV0poWldkcExXcDNkQzEwWlhOMExXRnNhbXBoWW1GbFoya3RhbmQwTFhSbGMzUXRZV3hxYW1GaVlXVm5hUzFxZDNRdGRHVnpkQzFoYkdwcVlXSmhaV2RwTFdwM2RDMTBaWE4wTFdGc2FtcGhZbUZsWjJrdGFuZDBMWFJsYzNRdFlXeHFhbUZpWVdWbmFTMXFkM1F0ZEdWemRDMWhiR3BxWVdKaFpXZHA=
    token-validity-in-seconds: 86400
    authorities-key: footprintsapi


logging:
  level:
    org.hibernate.sql: debug