spring:
  datasource:
    url: jdbc:h2:~/mtot;
    username: sa
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: application-s3.yaml, application-oauth.yaml, application-jwt.yaml
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

logging:
  level:
    org.hibernate.sql: debug


jwt:
  secretKey: ${JWT_SECRET_KEY}
  tokenValidPeriod: ${JWT_TOKEN_VALID_PERIOD}

google-oauth:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
header: ${HEADER}

s3:
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
  region: ${S3_REGION}
