spring:
  datasource:
    url: jdbc:h2:~/test;
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  config:
    import: application-jwt.yaml, application-oauth.yaml

logging:
  level:
    org.hibernate.sql: debug
