# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Secret check
      run: |
        echo "Secret key : ${{secrets.JWT_SECRET_KEY}}"

    - name: Inject secret keys
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/test/resources/application.yaml
      env:
        google-oauth.client-id: ${{secrets.GOOGLE_CLIENT_ID}}
        google-oauth.client-secret: ${{secrets.GOOGLE_CLIENT_SECRET}}
        header: ${{secrets.HEADER}}
        s3.accessKey: ${{secrets.S3_ACCESS_KEY}}
        s3.secretKey: ${{secrets.S3_SECRET_KEY}}
        s3.bucket: ${{secrets.S3_BUCKET}}
        s3.region: ${{secrets.S3_REGION}}
        spring.datasource.url: jdbc:h2:mem:mtot;
        spring.datasource.password: ${{secrets.H2_PASSWORD}}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
      
